### ISSUE TITLE
Fix set as not favourite in amendments

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2562] opened 2023-07-26 12:50 UTC
in amendends if several favourited amendments are selected and the favourite star is tried to be removed an Error is thrown and the favourite state stays the same.

**How to recreate:**
1. create two new amendments
2. navigate into amendments
3. select the two new amendments with multiselect
4. set them as favourite
5. try to remove the favourites again
6. Error is thrown: Can't create personal note without star or note. 

additional information: 
- the error is only thrown if at least two amendments never swtiched **from** favourite **to** not faviourite
- sometimes (with for me unknown requirements) it is also not possible to set them to favourite

**wanted behaviour:**
it should be possible to change the favourite state if amendments are selected via multiselect

**Comment by MSoeb** [comment] 2023-09-12 08:14
Dupe of issue #2692

**Closed by MSoeb** 2023-09-12 08:14 UTC
Labels: bug
