### ISSUE TITLE
Fix missing loading bar for a motion

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2719] opened 2023-08-29 08:56 UTC
**Current behaviour:**
if you move via the arrows in between the motions then the loading bar does not appear but the words 'undefined'

**Recreation:**
1. create at least two motions (I recommend long motion > 1000 words)
2. go into motion 1 
3. reload page 
4. press the arrow in the top right region to navigate to the next motion
5. no loading bar but _undefined_

**Wanted behaviour:**
The loading bar should also appear if you use the arrows to move in between motions

**Comment by reiterl** [comment] 2023-10-05 11:56
I cannot reproduce the problem on my developer setup. After clicking on the right-arrow the large motion instantly appears.

**Comment by jsangmeister** [comment] 2023-10-05 13:26
Maybe try killing the autoupdate service while you are on a motion detail view and then try to navigate via the arrow buttons.

**Comment by Elblinator** [comment] 2023-10-18 12:22
I tried it with more than 1000 motions (our biiiig dataset) and it still happens.

Apparently you need not only rather big motions but also a lot of them

**Comment by Elblinator** [comment] 2023-10-19 05:51
I also tried it again with my own localhost 
I have:
- 21 motions, 9 of them are amendments
- there are very long motions with +1000 words 
- but also 10 which have at most 5 words 

I can provoke the "undefined" if I skip through the motions (via arrow) very fast. But I can also see the "undefined" when I leisurely move from one motion to the other (also for motions with one word).

I am not doing anything else besides pressing the arrow.

**Comment by reiterl** [comment] 2024-02-23 08:47
I can reproduce this problem. I have 10 motions. Reload, go into the detail view, press in the arrow-navigation on next/prev. See "undefined" for a moment.

**Comment by reiterl** [comment] 2024-02-23 10:19
Mmh, the component which seems to have this failure is: `os-motion-detail-original-change-recommendations`.
TextLoaded doesn't seem to work right and doesn't show the mat-progress-bar. and there is a wrong html set to this
component in the beginning. (Sth like: "<span>...</span>undefined"). So the "undefined" is shown. I think the `motion-diff` part is setting the html. Strange.

**Comment by bastianjoel** [comment] 2024-08-15 08:24
could be addressed in #4023

**Closed** 2024-09-16 08:50 UTC
Labels: bug
