### ISSUE TITLE
Fix assignment_list, active_poll and operator subscription

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3776] opened 2024-06-13 13:23 UTC
**Current behaviour:**
If you are in several meetings (and are currently in Metting A) and you are in one election-detail-view then you still get the autoupdates from your other meetings for the assignment_list, active_poll and operator subscriptions

**Reproduction:**
1. create a user Ann who is in two meetings (both as delegate)
2. Meetings A : as Ann navigate into one election and open the console
3. Meetings B: as (super)admin create a new election and assignment 
4.  Meetings B: as (super)admin set A to present/not present
5. While the superadmin changes stuff in Meeting B, Ann gets the autoupdates while only having Meeting A open 

**Wanted behaviour:**
Meeting specific subscriptions should only be triggered while in side the meeting of question.
The three found subscriptions should be prevented to bled into other meetings

**Comment by bastianjoel** [comment] 2024-06-26 08:00
This is not a bug. It is intended that the `is_present_in_meeting_ids` changes when your presence status changes. 

The other subscriptions get notified because they were merged together with the operator subscription. However this does not trigger any repos and therefore also does not cause any performance issues.

**Closed by bastianjoel** 2024-06-26 08:00 UTC
Labels: bug
