### ISSUE TITLE
Updating a committee does not send the new title

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-client#332] opened 2021-07-01 10:19 UTC
Updating a committee form `/committees/$/edit-committee` does not send the title field.
The current payload is:

```
{
  "action": "committee.update",
  "data": [
    {
      "id": 2,
      "description": "",
      "organization_tag_ids": [],
      "user_ids": [2, 3],
      "forward_to_committee_ids": [],
      "receive_forwardings_from_committee_ids": [1]
    }
  ]
}
```

**Comment by GabrielInTheWorld** [comment] 2021-07-01 10:31
Duplicate of #324. -> will be fixed with #330.

**Closed** 2021-07-01 10:34 UTC
Labels: bug, client
