### ISSUE TITLE
pdf export doesn't display sub bullet points

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1582] opened 2022-09-11 19:01 UTC
Problem description: When exporting a motion with nested bullet points, these are not exported in the pdf file. The content in these bullet points is ignored and the bottom lines move further up. The pdf export is damaged. 

Reproduction:
1. open _meeting_
2. open _motions_
3. create new motion. Create nested bullet points in the motion text and save it.
4. after creating the motion, click on three-dot menu and select _pdf_. Then open the pdf file.

What should happen: All bullet points should be displayed correctly in the pdf file. No content should be missing. 

Motion in OpenSlides:
![Screenshot_20220911_210045](https://user-images.githubusercontent.com/105491030/189544625-17567543-e48d-49da-a036-4471d980abf9.png)

pdf file with missing content:
![Screenshot_20220911_210114](https://user-images.githubusercontent.com/105491030/189544613-b58ce876-d571-46f2-bb77-0620a6043f3b.png)

**Comment by jsangmeister** [comment] 2022-09-12 06:19
Sounds like a duplicate of https://github.com/OpenSlides/openslides-client/issues/1161

**Closed** 2022-09-13 14:41 UTC
Labels: bug, high
