### ISSUE TITLE
layout bug in motion call list

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1417] opened 2022-07-20 12:09 UTC
The counter on the top left side of the motion call list page has a bad layout. In contrast to similar counters, it is too close to the navigation menu.

Reproduction: Just open an empty motion call list in a meeting. Could be found in motions/three-dot-meni/call list

See counter "1 of 1"
![Screenshot_20220720_140148](https://user-images.githubusercontent.com/105491030/179976927-fdc49579-62a5-4e8d-8a1c-3dc6c3307b5e.png)
t

**Comment by jsangmeister** [comment] 2022-07-25 06:01
Duplicate of https://github.com/OpenSlides/openslides-client/issues/1331

**Closed by jsangmeister** 2022-07-25 06:01 UTC
Labels: bug
