### ISSUE TITLE
Dashboard / Tag menu: Possibility to change the color with a selection mask

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1420] opened 2022-07-20 13:30 UTC
Currently, the color for keywords can only be customized by color code and not by selection mask. The user is forced to search outside OS for the desired color code. This is unnecessary. In the Design menu, one can already choose the color freely in a selection menu or enter the RGB code. This possibility should also exist for the color selection for keywords.

Tag menu
![Screenshot_20220720_152911](https://user-images.githubusercontent.com/105491030/179994372-570d3a10-92eb-4c9e-bbbd-b7479a593228.png)

Compare Design
![Screenshot_20220720_152944](https://user-images.githubusercontent.com/105491030/179994498-cf6989d0-2385-48be-8569-76506b1b8cbc.png)

**Comment by jsangmeister** [comment] 2022-07-26 11:55
Duplicate of https://github.com/OpenSlides/openslides-client/issues/726. Keeping this issue since it's more detailled and up-to-date.

**Closed** 2022-10-19 13:47 UTC
Labels: feature
