### ISSUE TITLE
Motions: Voting possible, although the status does not allow it

### ISSUE THREAD

**Issue by alveolus** [OpenSlides/openslides-client#849] opened 2022-02-17 12:11 UTC
### Describe the bug
.../motions/...
It is possible to create a poll/vote in every status, although the workflow does not allow it.

### Expected behavior
Polls and the possibility to create a poll should only be possible if in the workflow .../motions/workflow/... the setting "Allow create poll" is active for the selected status. Otherwise not.

**Comment by emanuelschuetze** [comment] 2022-05-31 20:26
@alveolus Should be done. Please retest and close.

**Comment by rrenkert** [comment] 2022-08-29 13:07
@emanuelschuetze Is there a PR that fixes this one? We should not have open issues for month that are already done.
However I can not reproduce the issue in a short test.

**Comment by jsangmeister** [comment] 2022-08-29 13:12
At least in the backend this is not done yet. I will open an issue there

**Comment by luisa-beerboom** [comment] 2022-10-25 12:43
@rrenkert , @jsangmeister  since this seems to be resolved in both client and backend, I'll close this issue now

**Closed by luisa-beerboom** 2022-10-25 12:43 UTC
Labels: bug, difficulty: normal
