### ISSUE TITLE
Motion: Clicking twice on recommendation button generates error

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#1745] opened 2022-10-25 14:26 UTC
**Description:** If a motion has a recommendation and the user clicks twice on the selected recommendation, an error appears on the bottom of the page. 

![Screenshot_20221025_161747](https://user-images.githubusercontent.com/105491030/197798989-131af189-3c1f-4f80-9cb3-a6bfce7b4443.png)

![Screenshot_20221025_161910](https://user-images.githubusercontent.com/105491030/197799014-5979b906-2a54-4fd3-8427-6dbd38a3fe3b.png)

**Reproduction:**
1. open a meeting
2.  open settings/motions
3. search for the field "name of recommender" and add ABK to it 
4. open motions
5. create a motion
6. change in open motion under ABK the recommendation to Rejection. click it twice. -> error appears

**Expected behavior:** 
Best option: Clicking it twice should not be possible. The option should be grayed out. 
Alternativ: Clicking it twice results in nothing. Nothing happens. (This is the solution in OS3)

**Comment by bastianjoel** [comment] 2022-10-26 09:43
duplicate of #1742

**Closed** 2022-10-27 12:07 UTC
Labels: bug
