### ISSUE TITLE
Add and Sort submitters in the same instance

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2678] opened 2023-08-21 08:21 UTC
**Current behaviour:**
If a submitter is added and sorted without saving in between then an Error is thrown: Error: Id <nr> not in db_instances.

**Recreation:**
1. navigate to motions > motion < edit submitter
2. add participant A and B
3. sort resort A and B 
4. Error is thrown

**Wanted behaviour:**
Adding and sorting submitter should be possible without saving in between

**Comment by jsangmeister** [comment] 2023-08-22 10:36
This stems from the fact that the sort action is sent directly to the backend, while the "Add submitter" action is only sent after "save" is clicked. We already talked about this in a coordination meeting. I'm not sure though what the consensus was: Either we remove the save/cancel buttons completely and both actions are sent directly, or we keep the buttons and both actions are only sent on save. The latter means that the client needs to stagger the request to wait for the submitter id.

**Comment by rrenkert** [comment] 2023-08-22 12:53
Can not reproduce. Seems to be fixed by rtf?

**Closed by rrenkert** 2023-08-22 12:53 UTC
Labels: bug, needs info
