### ISSUE TITLE
Syntax Error: list_of_speakers_hide_contribution_count does not exist

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-client#3516] opened 2024-04-09 10:17 UTC
Open meeting from dashboard (in current 4.1.6 stable):
=> Autoupdate error:
`"field \"list_of_speakers_hide_contribution_count\": meeting/list_of_speakers_hide_contribution_count does not exist"`

**Comment by Elblinator** [comment] 2024-04-09 11:28
Some part of the reproduction is still unclear 
@emanuelschuetze if possible please complete the reproduction
Reproduction: 
1. Go into a meeting 
2. reload the page 
3. navigate to the dashboard
4. navigate into an other meeting

**Comment by bastianjoel** [comment] 2024-04-10 08:42
This is not reproducible

**Comment by reiterl** [comment] 2024-04-16 12:59
I think this was a problem with a too old autoupdate service. I cannot reproduce this.

**Comment by bastianjoel** [comment] 2024-04-16 13:36
I will close this now as there is no info provided since last week.

**Closed by bastianjoel** 2024-04-16 13:36 UTC
Labels: bug, needs investigation
