### ISSUE TITLE
Empty folders are displayed with the previous content

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#1192] opened 2022-05-30 06:38 UTC
1. go to https://demo.os4.openslides.com/11/mediafiles/3
2. click on `www` (empty folder)
3. the folder `www` persists in the display, but clicking it does not do anything

**Comment by GabrielInTheWorld** [comment] 2022-06-10 10:12
I cannot reproduce this behavior. Maybe, it was fixed by #1187

**Comment by jsangmeister** [comment] 2022-06-13 06:06
If you execute the steps described above in the demo (after logging in of course), the same behaviour still occurs, only that the folder does not even seem to be empty - if you reload on https://demo.os4.openslides.com/11/mediafiles/4, the file `openslides-logo.png` appears.

**Comment by luisa-beerboom** [comment] 2022-06-29 08:25
There seems to be a general problem with viewupdates of the mediafilelist when navigating between non-base-folder-folders, changing the priority of this to high, since it has been causing confusion

**Closed** 2022-07-08 11:36 UTC
Labels: bug, needs info, high, affected view: mediafile
