### ISSUE TITLE
Adjust client to backend translations

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-client#2055] opened 2023-02-23 09:29 UTC
See OpenSlides/openslides-backend#1437 for information

**Comment by jsangmeister** [comment] 2023-02-23 09:42
Duplicate of https://github.com/OpenSlides/openslides-client/issues/2007

**Closed by jsangmeister** 2023-02-23 09:42 UTC
Labels: feature, needs discussion

**Comment by luisa-beerboom** [comment] 2023-02-23 09:47
Oh, sorry I didn't see that one

**Comment by jsangmeister** [comment] 2023-02-23 10:11
no problem ;)
