### ISSUE TITLE
Link from autopilot to a projector is broken

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#1041] opened 2022-05-02 11:49 UTC

**Comment by rrenkert** [comment] 2022-05-11 09:27
This happens for delegates, not admins.

**Comment by rrenkert** [comment] 2022-05-11 09:38
duplicate of #1042 and will be fixed by #1054

**Comment by luisa-beerboom** [comment] 2022-05-11 15:31
This is actually a different Problem than the fullscreen projectors of #1042 and as of right now #1054 is not build to fix this

**Closed** 2022-05-17 21:42 UTC
Labels: bug, high, good first issue, difficulty: easy
