### ISSUE TITLE
Account/Participant export: Initial Password not always exported

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-client#4145] opened 2024-09-17 13:56 UTC
**Describe the bug**
A strange error occurs in the account/participant export; the inital password of some accounts are not exported. I've tried to reproduce it, but I can't. If you need further details please contact me.

**Expected behavior**
Account and participant export should always export the inital password.

**Comment by reiterl** [comment] 2024-09-23 09:51
Mmh, I cannot reproduce the failure. I looked at the code. 'default_password' is just a simple string field in User. I have
no idea why that happened. 
I tried: superadmin, account admin, reload before export. All works.

**Comment by reiterl** [comment] 2024-09-23 10:24
@MSoeb told me that the failure happens on a prod instance with account and participant csv exports.

**Comment by reiterl** [comment] 2024-09-23 12:16
I can reproduce the problem at the clone with the account-list and csv export. It seems to be that the default_password field is missing in the account_list subscription. One sign for this: I enter a account-detail view of a user and export, then the default_password will be in the export file.

**Comment by reiterl** [comment] 2024-09-23 12:18
I cannot reproduce the missing default_password for a participants list.

**Closed** 2024-09-24 10:23 UTC
Labels: bug
