### ISSUE TITLE
Improve Jitsi

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#857] opened 2022-02-17 20:20 UTC
### Discussed in https://github.com/OpenSlides/OpenSlides/discussions/6365

<div type='discussions-op-text'>

<sup>Originally posted by **111phil** February 17, 2022</sup>
Hi! As probably many of you have already experienced, the Jitsy video conference tool is unfortunately quite disappointing.

1. Many of our participants have trouble using it, e.g. because the browser demands mic and cam access, which only pops up once and then doesn't show up again.
2. Moreover, if you have different tabs open, it opens new videos for all of them, which is not only annoying, but also waisting a lot of bandwith.
3. Lastly, it could be helpful, if there was the possibility of showing different videos at the same time (e.g. for deaf sign interpreters). </div>

**Comment by bug0001** [comment] 2022-02-18 09:23
1 and 2 : I know that the Jitsi apps let you configure things (without the issue of the dialogue disappearing) and also have an option to disable video on start.

Can we provide people with links to the rooms so that they are able to use the Jitsi apps?

That may be one solution.

**Comment by jsangmeister** [comment] 2022-02-22 07:24
1) I know that @tsiegleauq had a lot of trouble with the permissions request of browsers. It is very well possible that there is no "good" solution for this - e.g. if the problem is that people deny the permissions explicitly the first time, browsers may not ask again in the future, since this would lead to potential "permission spam" from certain websites. So the only option is then to go into the browser settings and reset these permissions for OpenSlides. However, there could still be room for other improvements.
3) I think this is out of scope for the moment and maybe even for OS4. If one really needs this, they can provide a custom live stream where the second video is merged picture-in-picture into the main feed or something similar. I would imagine users which have need for this are also capable of this kind of live feed control.

**Comment by MSoeb** [comment] 2023-01-18 11:49
Point three refers to issue #856. It will be discussed in this context.

**Closed** 2024-08-22 10:06 UTC
Labels: needs discussion
