### ISSUE TITLE
Date and filesize of a mediafile is not correctly displayed

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#808] opened 2022-02-08 08:35 UTC
I _think_ the date of a mediafile is given in seconds but in the client accepted as ms. The filesize is not in a "human readable" format displayed.

**Comment by bug0001** [comment] 2022-02-09 16:13
Additions - the problem is present in the file list view, but not in the upload.

Solution

client/src/app/site/mediafiles/components/mediafile-list/mediafile-list.component.html

            <div class="foreground-icon" *ngIf="!mediafile.is_directory">
                <span>{{ getDateFromTimestamp(mediafile.create_timestamp) }} · {{ mediafile.filesize }}</span>
            </div>

this needs either a pipe (framework terminology) example mediafile.size | h... or h(file.size)

Except we already have that in another part of the application

client/src/app/shared/components/media-upload-content/media-upload-content.component.html

                <mat-icon [inline]="true">data_usage</mat-icon>
                {{ getReadableSize(file.mediafile.size) }}



client/src/app/shared/components/media-upload-content/media-upload-content.component.ts

    /**
     * Converts a file size in byte into human readable format
     *
     * @param bytes file size in bytes
     * @returns a readable file size representation
     */
    public getReadableSize(bytes: number): string {
        if (bytes === 0) {
            return `0 B`;
        }
        const unitLevel = Math.floor(Math.log(bytes) / Math.log(1024));
        bytes = +(bytes / Math.pow(1024, unitLevel)).toFixed(2);
        return `${bytes} ${[`B`, `kB`, `MB`, `GB`, `TB`][unitLevel]}`;
    }

**Comment by bug0002** [comment] 2022-02-24 18:00
pr #872 solves half the problem

the current view being 

x/x/1970, 2:x:x AM · 35.xx kB

**Comment by bug0002** [comment] 2022-02-25 06:54
Once this pr is merged the next steps would be :

- Removing the local function from the upload view, using the general pipe there
- Doing the date thing

**Comment by bug0002** [comment] 2022-02-26 10:29
openslides-client/client/src/app/site/mediafiles/models/view-mediafile.ts

    public get timestamp(): string {
        return this.mediafile.create_timestamp ? this.mediafile.create_timestamp : null;
    }


openslides-client/client/src/app/site/mediafiles/components/mediafile-list/mediafile-list.component.ts
I'm leaving my debugging notes here :+1: 
    public getDateFromTimestamp(timestamp: string): string {
        return new Date(timestamp).toLocaleString(this.translate.currentLang);
    }






"JavaScript stores dates as number of milliseconds since January 01, 1970, 00:00:00 UTC"


Solution


    public getDateFromTimestamp(timestamp: string): string {
        let timestamp2 = String(Number(timestamp)*1000);
        let timestamp3 = new Date(timestamp2);
        let timestamp4 = timestamp3.toString();
        // return timestamp;    1645722502
        // return timestamp2;   1645722502000
        // Date(1645722502000)  Sat Feb 26 2022 ...
        // return timestamp4;   Invalid date
        return timestamp4;
    }

Now it's an issue of data type conversion, or maybe something else.

**Closed** 2022-03-02 13:46 UTC
Labels: bug, good first issue
