### ISSUE TITLE
Call `/voted` url of vote service to retrieve information whether a user has already voted

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-client#645] opened 2021-11-16 09:12 UTC
See https://github.com/OpenSlides/openslides-vote-service/issues/57 for additional information and for the concept and https://github.com/OpenSlides/openslides-vote-service/pull/58 for the implementation details in the vote service.

Feel free to adjust milestone and/or priority as needed.

**Comment by jsangmeister** [comment] 2021-11-17 08:57
Done as part of https://github.com/OpenSlides/openslides-client/pull/640

**Comment by jsangmeister** [comment] 2021-12-01 14:27
Seems to not be working atm, @tsiegleauq @GabrielInTheWorld maybe you should talk about what's missing here.

**Comment by tsiegleauq** [comment] 2021-12-01 14:35
The client side seems to work correctly. The vote-service incorrectly returns false if the user has voted.

![image](https://user-images.githubusercontent.com/10233032/144253579-786ba357-8f32-40a2-b23e-09ac7078f06a.png)

**Comment by jsangmeister** [comment] 2021-12-01 14:59
See https://github.com/OpenSlides/openslides-vote-service/pull/58: The route returns only `true` for `STARTED` polls, in all other states it returns false.

I just tested it with @GabrielInTheWorld and the route seems to return an empty result for all calls, so I cannot verify whether the route works correctly in the started state. Maybe @ostcar can chime in? (although I supect the current state is described in the aforementioned PR...)

**Comment by ostcar** [comment] 2021-12-01 16:08
The vote-service does not only return the value for started polls, but for every state. But of cause, this is only possible, as long as the vote service has the data. After the poll is stopped, the backend calls the clear route of the vote service. So all data for this poll get deleted. So it is not possible to correctly return the question, if the user has voted.

**Comment by jsangmeister** [comment] 2021-12-02 09:01
Theoretically, the vote service could then request the data from the backend to always return correct results, but I don't even think this is necessary since we only need this info for `STARTED` polls. The workflow I tried with @GabrielInTheWorld was the following:

- Start a poll and vote in it
- Delete all local data and log in again

After going to the poll page, the UI said that we could vote again, although this was not possible. Also, looking at the network tab, the request to the `/voted` url returned `{}` as an response, even though the poll was still running and the vote service should have the data to answer it.

Also I notice now, it seemed like the client sent multiple requests to the url. @tsiegleauq was this just because the result was empty or does the client not save the result into local storage?

**Comment by ostcar** [comment] 2021-12-02 09:38
There could be a bug in the voted URL in the vote service.

Could you open an issue in the vote service repo and tell me step by step what I have to do to reproduce the bug?

**Comment by jsangmeister** [comment] 2021-12-02 10:10
Sure

**Comment by tsiegleauq** [comment] 2021-12-08 14:18
seems to be fixed in current vote service. Im getting `{"6":true}` on `https://localhost:8000/system/vote/voted?ids=6` after reload.

**Closed by tsiegleauq** 2021-12-08 14:18 UTC
Labels: high, client
